# Generated by Django 4.2.4 on 2024-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alternative_address',
            field=models.CharField(blank=True, default='alternative address', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alternative_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
