# Generated by Django 4.2.4 on 2024-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_alternative_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='acc_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alternative_address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
