# Generated by Django 4.2.4 on 2024-05-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('destination_acc', models.ManyToManyField(related_name='destination_account', to='main.account')),
                ('source_acc', models.ManyToManyField(related_name='source_account', to='main.account')),
            ],
        ),
    ]
