# Generated by Django 4.2.4 on 2024-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_acc',
            field=models.ManyToManyField(blank=True, related_name='destination_account', to='main.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_acc',
            field=models.ManyToManyField(blank=True, related_name='source_account', to='main.account'),
        ),
    ]
