# Generated by Django 4.2.4 on 2024-05-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source_acc',
        ),
    ]
