# Generated by Django 4.2.4 on 2024-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('fixedDeposit', 'FixedDeposit'), ('salary', 'Salary'), ('mmas', 'MMAs')], default='salary', max_length=20),
        ),
    ]
