# Generated by Django 4.2.4 on 2024-05-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_account_account_no_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
    ]
